### ISSUE TITLE
[Suggestion] Import/Export setup

### ISSUE THREAD

**Issue by SuperMalakan** [ZoltanTheDM/class-editor#1]
This would allow you to setup the classes once and only have to export the setup and import on subsequent worlds, saving the DM a lot of time.

**Comment by ZoltanTheDM** [comment]
That is a good idea. However it would only work for items in compendiums. Which wouldn't be the end of the world but could work.

**Comment by MaxPat931** [comment]
I'm sure it's a stretch to ask, but if it could somehow work with what I'd set up with the Custom Classes module that would be awesome

**Comment by ZoltanTheDM** [comment]
Added the ability to copy and paste the driving json in `0.5.0`. Wouldn't work with sharing lists between worlds unless they use the same compendiums
