### ISSUE TITLE
Allow for user custimization of Class/Subclass

### ISSUE THREAD

**Issue by MaxPat931** [ZoltanTheDM/class-editor#2]
Allow a user to select a compendium to generate Classes, and a way to define the Subclass options (Artificer, Tasha's Subclasses are currently missing, and no way to add homebrew)

Classes could be handled by Items in a Compendium, but I think Subclasses would need to be defined some other way as there isn't a Subclass item type.

**Comment by ZoltanTheDM** [comment]
For now you can manually edit the json to add classes and subclasses. Not the ideal solution but it works.

It is possible to search all items to add new classes etc. It would be another Dialog but it should work. Only thing that is needed is time

**Comment by Ikabodo** [comment]
> For now you can manually edit the json to add classes and subclasses. Not the ideal solution but it works.

Super nice module. I was just about to make my players leveling easier when I realised Way of Mercy was missing. But if I edit the json, will that not be overwritten when there is an update?

**Comment by ZoltanTheDM** [comment]
> 
> 
> > For now you can manually edit the json to add classes and subclasses. Not the ideal solution but it works.
> 
> Super nice module. I was just about to make my players leveling easier when I realised Way of Mercy was missing. But if I edit the json, will that not be overwritten when there is an update?

No it should not, the data for auto leveling is stored in the world settings. This module is just about interfacing with that stored json. The only worry is that the interface with the dnd5e system changes. But if that happen I think I can just change the [underlying module](https://github.com/ZoltanTheDM/Class-Exposure).

At least that is the plan

**Comment by ZotyDev** [comment]
Might be a dumb question, but what is the path to the json?

**Comment by Ikabodo** [comment]
> Might be a dumb question, but what is the path to the json?

Click the import/export button. Copy that json, edit it, then paste it back and import.

Works like a charm to just add something like this.
```
      "circle-of-the-dunes": {
        "label": "Circle of the Dunes",
        "source": "PHB pg. X",
        "features": {}
      },
```

**Comment by mhelvin505** [comment]
After setting up the json manually for a custom class none of the features are being automatically added. Could you explain more on how to get custom classes working?

**Comment by ravingdragoon** [comment]
> After setting up the json manually for a custom class none of the features are being automatically added. Could you explain more on how to get custom classes working?

I am having the same issue. Any advice?

**Comment by ravingdragoon** [comment]
Has this module been abandoned?

**Comment by Wiggledude** [comment]
Having the same issue, even after adjusting the json, it won't add the subclass skills on the sheet

**Comment by ItsJawn** [comment]
#6 For those wanting to add classes/subclasses
Made a little guide. Hope it helps!
