### ISSUE TITLE
Tidy5e CSS conflict

### ISSUE THREAD

**Issue by M0nk3yy** [ZoltanTheDM/class-editor#3]
When the Class Editor mod is enabled, the item rows in Tidy5e get all fat.

Standard:

![image](https://user-images.githubusercontent.com/66137312/130360152-fa19b358-8981-42ba-9720-d00779518848.png)

Class Editor enabled:

![image](https://user-images.githubusercontent.com/66137312/130360177-c9a461a4-923c-4ea2-9242-2b7ee134c1ff.png)

**Comment by ZoltanTheDM** [comment]
Fixed in `0.5.0`
